[package]
name = "lineio"
version = "0.1.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A simple line reader for files - skipping blank lines and comments"
repository = "https://github.com/profmadden/lineio"
exclude = ["src/main.rs"]


[dependencies]
